apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "mcp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "mcp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.mcpServer.port }}
      targetPort: {{ .Values.mcpServer.port }}
      name: http
